{
  lib,
  config,
  den,
  ...
}:
{
  den.aspects.qbittorrent = {
    includes = [
      den.aspects.podman
    ];

    nixos = { config, ... }: {
      # Runtime
      virtualisation.podman = {
        enable = true;
        autoPrune.enable = true;
        dockerCompat = true;
      };

      # Enable container name DNS for all Podman networks.
      networking.firewall.interfaces =
        let
          matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
        in
        {
          "${matchAll}".allowedUDPPorts = [ 53 ];
        };

      virtualisation.oci-containers.backend = "podman";

      # Containers
      virtualisation.oci-containers.containers."qbittorrent" = {
        image = "lscr.io/linuxserver/qbittorrent:latest";
        environment = {
          "DOCKER_MODS" = "ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest";
          "PGID" = "1000";
          "PUID" = "1000";
          "TORRENTING_PORT" = "6881";
          "TZ" = "Asia/Kuching";
          "WEBUI_PORT" = "8080";
        };
        volumes = [
          "/home/itm154/.data/torrents:/data/torrents:rw"
          "/home/itm154/.docker/qbittorrent/config:/config:rw"
        ];
        ports = [
          "6881:6881/tcp"
          "6881:6881/udp"
        ];
        log-driver = "journald";
        extraOptions = [
          "--network-alias=qbittorrent"
          # "--network=web-proxy"
        ];
      };
      systemd.services."podman-qbittorrent" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "always";
        };
        partOf = [
          "podman-compose-qbittorrent-root.target"
        ];
        wantedBy = [
          "podman-compose-qbittorrent-root.target"
        ];
      };

      # Root service
      # When started, this will automatically create all resources and start
      # the containers. When stopped, this will teardown all resources.
      systemd.targets."podman-compose-qbittorrent-root" = {
        unitConfig = {
          Description = "Root target generated by compose2nix.";
        };
        wantedBy = [ "multi-user.target" ];
      };
    };
  };
}
